# Generated by Django 4.2.5 on 2023-09-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='proyect',
            new_name='project',
        ),
    ]
